# Generated by Django 4.2 on 2023-04-28 08:06

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='单价')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('freight', models.IntegerField(default=0, verbose_name='运费')),
                ('origin', models.CharField(max_length=20, verbose_name='产地')),
                ('pro_type', models.CharField(choices=[('ncp', '农产品'), ('sg', '水果'), ('ls', '零食')], default='ls', max_length=3, verbose_name='分类')),
                ('buyers', models.IntegerField(default=0, verbose_name='购买人数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论人数')),
                ('details', ckeditor.fields.RichTextField()),
                ('mainimg', models.ImageField(default='', upload_to='product/img/%Y/%m', verbose_name='商品主图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'tb_product',
            },
        ),
        migrations.CreateModel(
            name='ProPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/%Y/%m', verbose_name='商品图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'tb_img',
            },
        ),
    ]
